{{- $debugPod := .Values.debugPod -}}
{{ if $debugPod }}
{{- $root := . -}}
{{- $nodeIdx := .Values.nodeIdx -}}
{{- range $nIdx := untilStep 0 (.Values.nodeNum|int) 1 -}}
{{ if or (not $nodeIdx) (eq $nIdx ($nodeIdx|int)) }}
---
apiVersion: v1
kind: Pod
metadata:
  namespace: '{{ $root.Values.namespace }}'
  name: '{{ $root.Values.debugPodName }}-{{ $nIdx }}'
  labels:
    type: 'sds-debug'
{{- with $root.Values.labels -}}
{{ toYaml . | nindent 4 }}
{{ end }}
    app.kubernetes.io/instance: sds
    app.kubernetes.io/managed-by: Helm
    app.kubernetes.io/name: sds
spec:
{{ if gt ($root.Values.nodeNum|int) 1 }}
  affinity:
    podAntiAffinity:
      requiredDuringSchedulingIgnoredDuringExecution:
      - labelSelector:
          matchExpressions:
          - key: type
            operator: In
            values:
            - sds-debug
        topologyKey: kubernetes.io/hostname
{{ end }}
  containers:
  - command:
    - {{ $root.Values.debugCommand }}
{{ if $root.Values.debugCommandArgs }}
    args:
{{- with $root.Values.debugCommandArgs -}}
{{ toYaml . | nindent 6 }}
{{ end }}
{{ end }}
{{ if $root.Values.useResourcesLimits }}
    resources:
      requests:
        memory: '{{ $root.Values.requestsMemory }}'
        cpu: '{{ $root.Values.requestsCPU }}'
      limits:
        memory: '{{ $root.Values.limitsMemory }}'
        cpu: '{{ $root.Values.limitsCPU }}'
{{ end }}
    env:
    - name: SDS_CSV_PREFIX
      value: 'debug_jobs'
    - name: SDS_FIXTURES_RE
      value: '{{ $root.Values.fixturesRE }}'
    - name: SDS_DATASOURCES_RE
      value: '{{ $root.Values.datasourcesRE }}'
    - name: SDS_PROJECTS_RE
      value: '{{ $root.Values.projectsRE }}'
    - name: SDS_ENDPOINTS_RE
      value: '{{ $root.Values.endpointsRE }}'
    - name: SDS_TASKS_RE
      value: '{{ $root.Values.tasksRE }}'
    - name: SDS_FIXTURES_SKIP_RE
      value: '{{ $root.Values.fixturesSkipRE }}'
    - name: SDS_DATASOURCES_SKIP_RE
      value: '{{ $root.Values.datasourcesSkipRE }}'
    - name: SDS_PROJECTS_SKIP_RE
      value: '{{ $root.Values.projectsSkipRE }}'
    - name: SDS_ENDPOINTS_SKIP_RE
      value: '{{ $root.Values.endpointsSkipRE }}'
    - name: SDS_TASKS_SKIP_RE
      value: '{{ $root.Values.tasksSkipRE }}'
    - name: SDS_DRY_RUN
      value: '{{ $root.Values.dryRun }}'
    - name: SDS_DRY_RUN_CODE
      value: '{{ $root.Values.dryRunCode }}'
    - name: SDS_DRY_RUN_SECONDS
      value: '{{ $root.Values.dryRunSeconds }}'
    - name: SDS_TIMEOUT_SECONDS
      value: '{{ $root.Values.timeoutSeconds }}'
    - name: SDS_TASK_TIMEOUT_SECONDS
      value: '{{ $root.Values.taskTimeoutSeconds }}'
    - name: SDS_N_LONGEST
      value: '{{ $root.Values.nLongest }}'
    - name: SDS_STRIP_ERROR_SIZE
      value: '{{ $root.Values.stripErrorSize }}'
    - name: SDS_SKIP_SH
      value: '{{ $root.Values.skipSH }}'
    - name: SDS_SKIP_DATA
      value: '{{ $root.Values.skipData }}'
    - name: SDS_SKIP_ES_DATA
      value: '{{ $root.Values.skipEsData }}'
    - name: SDS_SKIP_ES_LOG
      value: '{{ $root.Values.skipEsLog }}'
    - name: SDS_SKIP_CHECK_FREQ
      value: '{{ $root.Values.skipCheckFreq }}'
    - name: SDS_SKIP_AFFS
      value: '{{ $root.Values.skipAffs }}'
    - name: SDS_SKIP_ALIASES
      value: '{{ $root.Values.skipAliases }}'
    - name: SDS_SKIP_DEDUP
      value: '{{ $root.Values.skipDedup }}'
    - name: SDS_SKIP_EXTERNAL
      value: '{{ $root.Values.skipExternal }}'
    - name: SDS_SKIP_PROJECT
      value: '{{ $root.Values.skipProject }}'
    - name: SDS_SKIP_PROJECT_TS
      value: '{{ $root.Values.skipProjectTS }}'
    - name: SDS_SKIP_SYNC_INFO
      value: '{{ $root.Values.skipSyncInfo }}'
    - name: SDS_SKIP_VALIDATE_GITHUB_API
      value: '{{ $root.Values.skipValGitHubAPI }}'
    - name: SDS_SKIP_SORT_DURATION
      value: '{{ $root.Values.skipSortDuration }}'
    - name: SDS_SKIP_MERGE
      value: '{{ $root.Values.skipMerge }}'
    - name: SDS_SKIP_HIDE_EMAILS
      value: '{{ $root.Values.skipHideEmails }}'
    - name: SDS_SKIP_ORG_MAP
      value: '{{ $root.Values.skipOrgMap }}'
    - name: SDS_SKIP_DET_AFF_RANGE
      value: '{{ $root.Values.skipDetAffRange }}'
    - name: SDS_SKIP_P2O
      value: '{{ $root.Values.skipP2O }}'
    - name: SDS_SKIP_SSAW
      value: '{{ $root.Values.skipSSAW }}'
    - name: SDS_ONLY_VALIDATE
      value: '{{ $root.Values.onlyValidate }}'
    - name: SDS_ONLY_P2O
      value: '{{ $root.Values.onlyP2O }}'
    - name: SDS_NO_MULTI_ALIASES
      value: '{{ $root.Values.noMultiAliases }}'
    - name: SDS_CLEANUP_ALIASES
      value: '{{ $root.Values.cleanupAliases }}'
    - name: SDS_SKIP_DROP_UNUSED
      value: '{{ $root.Values.skipDropUnused }}'
    - name: SDS_NODE_HASH
      value: '{{ $root.Values.nodeHash }}'
    - name: SDS_NODE_NUM
      value: '{{ $root.Values.nodeNum }}'
    - name: SDS_NODE_IDX
      value: '{{ $nIdx }}'
    - name: SDS_MAXRETRY
      value: '{{ $root.Values.sdsMaxRetry }}'
    - name: SDS_DEBUG
      value: '{{ $root.Values.sdsDebug }}'
    - name: SDS_CMDDEBUG
      value: '{{ $root.Values.sdsCmdDebug }}'
    - name: SDS_ST
      value: '{{ $root.Values.sdsST }}'
    - name: SDS_NCPUS
      value: '{{ $root.Values.sdsNCPUs }}'
    - name: SDS_NCPUS_SCALE
      value: '{{ $root.Values.sdsNCPUsScale }}'
    - name: SDS_CTXOUT
      value: '{{ $root.Values.sdsCtxOut }}'
    - name: SDS_SKIPTIME
      value: '{{ $root.Values.sdsSkipTime }}'
    - name: SDS_ES_BULKSIZE
      value: '{{ $root.Values.esBulkSize }}'
    - name: SDS_LATEST_ITEMS
      value: '{{ $root.Values.latestItems }}'
    - name: SDS_SCROLL_WAIT
      value: '{{ $root.Values.scrollWait }}'
    - name: SDS_SCROLL_SIZE
      value: '{{ $root.Values.scrollSize }}'
    - name: SDS_SILENT
      value: '{{ $root.Values.silent }}'
    - name: SDS_SKIP_REENRICH
      value: '{{ $root.Values.skipReenrich }}'
    - name: SDS_MAX_DELETE_TRIALS
      value: '{{ $root.Values.maxDeleteTrials }}'
    - name: BRANCH
      value: '{{ $root.Values.deployEnv }}'
    - name: SDS_SSAW_FREQ
      value: '{{ $root.Values.ssawFreq }}'
    - name: SDS_SSAW_URL
      valueFrom:
        secretKeyRef:
          name: {{ $root.Values.ssawSecret }}
          key: SSAW_URL.secret
    - name: AFFILIATION_API_URL
      valueFrom:
        secretKeyRef:
          name: {{ $root.Values.apiSecret }}
          key: AFFILIATION_API_URL.secret
    - name: SH_USER
      valueFrom:
        secretKeyRef:
          name: {{ $root.Values.shSecret }}
          key: SH_USER.secret
    - name: SH_HOST
      valueFrom:
        secretKeyRef:
          name: {{ $root.Values.shSecret }}
          key: SH_HOST.secret
    - name: SH_PORT
      valueFrom:
        secretKeyRef:
          name: {{ $root.Values.shSecret }}
          key: SH_PORT.secret
    - name: SH_PASS
      valueFrom:
        secretKeyRef:
          name: {{ $root.Values.shSecret }}
          key: SH_PASS.secret
    - name: SH_DB
      valueFrom:
        secretKeyRef:
          name: {{ $root.Values.shSecret }}
          key: SH_DB.secret
    - name: SDS_ES_URL
      valueFrom:
        secretKeyRef:
          name: {{ $root.Values.esSecret }}
          key: ES_URL.secret
    - name: SDS_GITHUB_OAUTH
      valueFrom:
        secretKeyRef:
          name: {{ $root.Values.githubSecret }}
          key: GITHUB_OAUTH.secret
    - name: AUTH0_URL
      valueFrom:
        secretKeyRef:
          name: {{ $root.Values.auth0Secret }}
          key: AUTH0_URL.secret
    - name: AUTH0_AUDIENCE
      valueFrom:
        secretKeyRef:
          name: {{ $root.Values.auth0Secret }}
          key: AUTH0_AUDIENCE.secret
    - name: AUTH0_CLIENT_ID
      valueFrom:
        secretKeyRef:
          name: {{ $root.Values.auth0Secret }}
          key: AUTH0_CLIENT_ID.secret
    - name: AUTH0_CLIENT_SECRET
      valueFrom:
        secretKeyRef:
          name: {{ $root.Values.auth0Secret }}
          key: AUTH0_CLIENT_SECRET.secret
    - name: ZIPPASS
      valueFrom:
        secretKeyRef:
          name: {{ $root.Values.zipSecret }}
          key: ZIPPASS.secret
{{ if $root.Values.useRepoAccess }}
    - name: REPO_ACCESS
      valueFrom:
        secretKeyRef:
          name: {{ $root.Values.repoSecret }}
          key: REPO_ACCESS.secret
{{ end }}
{{ if $root.Values.onlyValidate }}
    image: '{{ $root.Values.validateImage }}'
{{ else }}
    image: '{{ $root.Values.debugImage }}-{{ $root.Values.deployEnv }}'
{{ end }}
    imagePullPolicy: {{ $root.Values.imagePullPolicy }}
    name: '{{ $root.Values.debugPodName }}-{{ $nIdx }}'
    volumeMounts:
    - name: '{{ $root.Values.pvName }}-{{ $nIdx }}'
      mountPath: '{{ $root.Values.pvMountPath }}'
  volumes:
  - name: '{{ $root.Values.pvName }}-{{ $nIdx }}'
    persistentVolumeClaim:
      claimName: '{{ $root.Values.pvName }}-{{ $nIdx }}'
  restartPolicy: {{ $root.Values.imageRestartPolicy }}
{{ if $root.Values.useNodeSelector }}
  nodeSelector:
{{- with $root.Values.nodeSelector -}}
{{ toYaml . | nindent 4 }}
{{ end }}
{{ end }}
{{ end }}
{{ end }}
{{ end }}
