{{- $skipSecrets := .Values.skipSecrets -}}
{{ if not $skipSecrets }}
{{- $skipSHSecret := .Values.skipSHSecret -}}
{{ if not $skipSHSecret }}
# SH secret starts
{{- $shUser := or .Values.shUser (.Files.Get (printf "secrets/SH_USER.%s.secret" .Values.deployEnv)) -}}
{{- $shHost := or .Values.shHost (.Files.Get (printf "secrets/SH_HOST.%s.secret" .Values.deployEnv)) -}}
{{- $shPort := or .Values.shPort (.Files.Get (printf "secrets/SH_PORT.%s.secret" .Values.deployEnv)) -}}
{{- $shPass := or .Values.shPass (.Files.Get (printf "secrets/SH_PASS.%s.secret" .Values.deployEnv)) -}}
{{- $shDB := or .Values.shDB (.Files.Get (printf "secrets/SH_DB.%s.secret" .Values.deployEnv)) -}}
{{ if and $shUser $shPort $shHost $shPass $shDB }}
---
apiVersion: v1
data:
  SH_USER.secret: {{ $shUser | b64enc }}
  SH_HOST.secret: {{ $shHost | b64enc }}
  SH_PORT.secret: {{ $shPort | b64enc }}
  SH_PASS.secret: {{ $shPass | b64enc }}
  SH_DB.secret: {{ $shDB | b64enc }}
kind: Secret
metadata:
  namespace: '{{ .Values.namespace }}'
  name: {{ .Values.shSecret }}
  labels:
    type: 'secret'
{{- with .Values.labels -}}
{{ toYaml . | nindent 4 }}
{{ end }}
    app.kubernetes.io/name: {{ include "sds-helm.name" . }}
    helm.sh/chart: {{ include "sds-helm.chart" . }}
    app.kubernetes.io/instance: {{ .Release.Name }}
    app.kubernetes.io/managed-by: {{ .Release.Service }}
type: {{ .Values.secretType }}
{{ else }}
missing_one_or_more_sh_secrets: "Please take a look at the NOTES.txt file"
{{ end }}
# SH secret ends
{{ end }}
{{- $skipESSecret := .Values.skipESSecret -}}
{{ if not $skipESSecret }}
# ES secret starts
{{- $esURL := or .Values.esURL (.Files.Get (printf "secrets/ES_URL.%s.secret" .Values.deployEnv)) -}}
{{ if $esURL }}
---
apiVersion: v1
data:
  ES_URL.secret: {{ $esURL | b64enc }}
kind: Secret
metadata:
  namespace: '{{ .Values.namespace }}'
  name: {{ .Values.esSecret }}
  labels:
    type: 'secret'
{{- with .Values.labels -}}
{{ toYaml . | nindent 4 }}
{{ end }}
    app.kubernetes.io/name: {{ include "sds-helm.name" . }}
    helm.sh/chart: {{ include "sds-helm.chart" . }}
    app.kubernetes.io/instance: {{ .Release.Name }}
    app.kubernetes.io/managed-by: {{ .Release.Service }}
type: {{ .Values.secretType }}
{{ else }}
missing_es_secret: "Please take a look at the NOTES.txt file"
{{ end }}
# ES secret ends
{{ end }}
{{- $skipZipSecret := .Values.skipZipSecret -}}
{{ if not $skipZipSecret }}
# ZIP secret starts
{{- $zipPass := or .Values.zipPass (.Files.Get "secrets/ZIPPASS.secret") -}}
{{ if $zipPass }}
---
apiVersion: v1
data:
  ZIPPASS.secret: {{ $zipPass | b64enc }}
kind: Secret
metadata:
  namespace: '{{ .Values.namespace }}'
  name: {{ .Values.zipSecret }}
  labels:
    type: 'secret'
{{- with .Values.labels -}}
{{ toYaml . | nindent 4 }}
{{ end }}
    app.kubernetes.io/name: {{ include "sds-helm.name" . }}
    helm.sh/chart: {{ include "sds-helm.chart" . }}
    app.kubernetes.io/instance: {{ .Release.Name }}
    app.kubernetes.io/managed-by: {{ .Release.Service }}
type: {{ .Values.secretType }}
{{ else }}
missing_zip_secret: "Please take a look at the NOTES.txt file"
{{ end }}
# ZIP secret ends
{{ end }}
{{- $skipRepoSecret := .Values.skipRepoSecret -}}
{{ if not $skipRepoSecret }}
# Repo access secret starts
{{- $repoAccess := or .Values.repoAccess (.Files.Get "secrets/REPO_ACCESS.secret") -}}
{{ if $repoAccess }}
---
apiVersion: v1
data:
  REPO_ACCESS.secret: {{ $repoAccess | b64enc }}
kind: Secret
metadata:
  namespace: '{{ .Values.namespace }}'
  name: {{ .Values.repoSecret }}
  labels:
    type: 'secret'
{{- with .Values.labels -}}
{{ toYaml . | nindent 4 }}
{{ end }}
    app.kubernetes.io/name: {{ include "sds-helm.name" . }}
    helm.sh/chart: {{ include "sds-helm.chart" . }}
    app.kubernetes.io/instance: {{ .Release.Name }}
    app.kubernetes.io/managed-by: {{ .Release.Service }}
type: {{ .Values.secretType }}
{{ else }}
missing_repo_access_secret: "Please take a look at the NOTES.txt file"
{{ end }}
# Repo access secret ends
{{ end }}
{{- $skipGithubSecret := .Values.skipGithubSecret -}}
{{ if not $skipGithubSecret }}
# GitHub secret starts
{{- $githubOAuth := or .Values.githubOAuth (.Files.Get "secrets/GITHUB_OAUTH.secret") -}}
{{ if $githubOAuth }}
---
apiVersion: v1
data:
  GITHUB_OAUTH.secret: {{ $githubOAuth | b64enc }}
kind: Secret
metadata:
  namespace: '{{ .Values.namespace }}'
  name: {{ .Values.githubSecret }}
  labels:
    type: 'secret'
{{- with .Values.labels -}}
{{ toYaml . | nindent 4 }}
{{ end }}
    app.kubernetes.io/name: {{ include "sds-helm.name" . }}
    helm.sh/chart: {{ include "sds-helm.chart" . }}
    app.kubernetes.io/instance: {{ .Release.Name }}
    app.kubernetes.io/managed-by: {{ .Release.Service }}
type: {{ .Values.secretType }}
{{ else }}
missing_github_secret: "Please take a look at the NOTES.txt file"
{{ end }}
# GitHub secret ends
{{ end }}
{{- $skipAuth0Secret := .Values.skipAuth0Secret -}}
{{ if not $skipAuth0Secret }}
# Auth0 secret starts
{{- $auth0URL := or .Values.auth0URL (.Files.Get (printf "secrets/AUTH0_URL.%s.secret" .Values.deployEnv)) -}}
{{- $auth0Audience := or .Values.auth0Audience (.Files.Get (printf "secrets/AUTH0_AUDIENCE.%s.secret" .Values.deployEnv)) -}}
{{- $auth0ClientID := or .Values.auth0ClientID (.Files.Get (printf "secrets/AUTH0_CLIENT_ID.%s.secret" .Values.deployEnv)) -}}
{{- $auth0ClientSecret := or .Values.auth0ClientSecret (.Files.Get (printf "secrets/AUTH0_CLIENT_SECRET.%s.secret" .Values.deployEnv)) -}}
{{- $auth0Data := or .Values.auth0Data (.Files.Get (printf "secrets/AUTH0_DATA.%s.secret" .Values.deployEnv)) -}}
{{ if and $auth0URL $auth0Audience $auth0ClientID $auth0ClientSecret $auth0Data }}
---
apiVersion: v1
data:
  AUTH0_URL.secret: {{ $auth0URL | b64enc }}
  AUTH0_AUDIENCE.secret: {{ $auth0Audience | b64enc }}
  AUTH0_CLIENT_ID.secret: {{ $auth0ClientID | b64enc }}
  AUTH0_CLIENT_SECRET.secret: {{ $auth0ClientSecret | b64enc }}
  AUTH0_DATA.secret: {{ $auth0Data | b64enc }}
kind: Secret
metadata:
  namespace: '{{ .Values.namespace }}'
  name: {{ .Values.auth0Secret }}
  labels:
    type: 'secret'
{{- with .Values.labels -}}
{{ toYaml . | nindent 4 }}
{{ end }}
    app.kubernetes.io/name: {{ include "sds-helm.name" . }}
    helm.sh/chart: {{ include "sds-helm.chart" . }}
    app.kubernetes.io/instance: {{ .Release.Name }}
    app.kubernetes.io/managed-by: {{ .Release.Service }}
type: {{ .Values.secretType }}
{{ else }}
missing_one_or_more_auth0_secrets: "Please take a look at the NOTES.txt file"
{{ end }}
# Auth0 secret ends
{{ end }}
{{- $skipSSAWSecret := .Values.skipSSAWSecret -}}
{{ if not $skipSSAWSecret }}
# SSAW secret starts
{{ $ssawURL := or .Values.ssawURL (.Files.Get (printf "secrets/SSAW_URL.%s.secret" .Values.deployEnv)) -}}
---
apiVersion: v1
data:
  SSAW_URL.secret: {{ $ssawURL | b64enc }}
kind: Secret
metadata:
  namespace: '{{ .Values.namespace }}'
  name: {{ .Values.ssawSecret }}
  labels:
    type: 'secret'
{{- with .Values.labels -}}
{{ toYaml . | nindent 4 }}
{{ end }}
    app.kubernetes.io/name: {{ include "sds-helm.name" . }}
    helm.sh/chart: {{ include "sds-helm.chart" . }}
    app.kubernetes.io/instance: {{ .Release.Name }}
    app.kubernetes.io/managed-by: {{ .Release.Service }}
type: {{ .Values.secretType }}
# SSAW secret ends
{{ end }}
{{- $skipAPISecret := .Values.skipAPISecret -}}
{{ if not $skipAPISecret }}
# API secret starts
{{ $affiliationAPIURL := or .Values.affiliationAPIURL (.Files.Get (printf "secrets/AFFILIATION_API_URL.%s.secret" .Values.deployEnv)) -}}
{{ $metricsAPIURL := or .Values.metricsAPIURL (.Files.Get (printf "secrets/METRICS_API_URL.%s.secret" .Values.deployEnv)) -}}
---
apiVersion: v1
data:
  AFFILIATION_API_URL.secret: {{ $affiliationAPIURL | b64enc }}
  METRICS_API_URL.secret: {{ $metricsAPIURL | b64enc }}
kind: Secret
metadata:
  namespace: '{{ .Values.namespace }}'
  name: {{ .Values.apiSecret }}
  labels:
    type: 'secret'
{{- with .Values.labels -}}
{{ toYaml . | nindent 4 }}
{{ end }}
    app.kubernetes.io/name: {{ include "sds-helm.name" . }}
    helm.sh/chart: {{ include "sds-helm.chart" . }}
    app.kubernetes.io/instance: {{ .Release.Name }}
    app.kubernetes.io/managed-by: {{ .Release.Service }}
type: {{ .Values.secretType }}
# API secret ends
{{ end }}
{{- $skipSSOSecret := .Values.skipSSOSecret -}}
{{ if not $skipSSOSecret }}
# SSO secret starts
{{- $ssoAPIKey := or .Values.ssoAPIKey (.Files.Get (printf "secrets/SSO_API_KEY.%s.secret" .Values.deployEnv)) -}}
{{- $ssoAPISecret := or .Values.ssoAPISecret (.Files.Get (printf "secrets/SSO_API_SECRET.%s.secret" .Values.deployEnv)) -}}
{{- $ssoAudience := or .Values.ssoAudience (.Files.Get (printf "secrets/SSO_AUDIENCE.%s.secret" .Values.deployEnv)) -}}
{{- $ssoUserService := or .Values.ssoUserService (.Files.Get (printf "secrets/SSO_USER_SERVICE.%s.secret" .Values.deployEnv)) -}}
{{- $userServiceURL := or .Values.userServiceURL (.Files.Get (printf "secrets/USER_SERVICE_URL.%s.secret" .Values.deployEnv)) -}}
{{ if and $ssoAPIKey $ssoAPISecret $ssoAudience $ssoUserService $userServiceURL }}
---
apiVersion: v1
data:
  SSO_API_KEY.secret: {{ $ssoAPIKey | b64enc }}
  SSO_API_SECRET.secret: {{ $ssoAPISecret | b64enc }}
  SSO_AUDIENCE.secret: {{ $ssoAudience | b64enc }}
  SSO_USER_SERVICE.secret: {{ $ssoUserService | b64enc }}
  USER_SERVICE_URL.secret: {{ $userServiceURL | b64enc }}
kind: Secret
metadata:
  namespace: '{{ .Values.namespace }}'
  name: {{ .Values.ssoSecret }}
  labels:
    type: 'secret'
{{- with .Values.labels -}}
{{ toYaml . | nindent 4 }}
{{ end }}
    app.kubernetes.io/name: {{ include "sds-helm.name" . }}
    helm.sh/chart: {{ include "sds-helm.chart" . }}
    app.kubernetes.io/instance: {{ .Release.Name }}
    app.kubernetes.io/managed-by: {{ .Release.Service }}
type: {{ .Values.secretType }}
{{ else }}
missing_sso_secret: "Please take a look at the NOTES.txt file"
{{ end }}
# SSO secret ends
{{ end }}
{{ end }}
