---
kind: PersistentVolumeClaim
apiVersion: v1
metadata:
  namespace: default
  name: pvtest
spec:
  accessModes:
    - ReadWriteOnce
  storageClassName: openebs-hostpath
  resources:
    requests:
      storage: 1Gi
