#!/bin/bash
if [ -z "${API_KEY}" ]
then
  echo -n "GitHub API key: "
  read -s API_KEY
fi
if [ -z "${PASS}" ]
then
  echo -n "SortingHat DB Password: "
  read -s PASS
fi
if [ -z "${IDENTITIES}" ]
then
  p2o.py --enrich --index github_raw --index-enrich github -e http://localhost:9200 --no_inc --debug --db-host localhost --db-sortinghat shdb --db-user shuser --db-password "${PASS}" github opennetworkinglab onos --category issue -t "${API_KEY}" --sleep-for-rate > .perceval_onos.github.log || exit 2
  p2o.py --enrich --index github_raw --index-enrich github -e http://localhost:9200 --no_inc --debug --db-host localhost --db-sortinghat shdb --db-user shuser --db-password "${PASS}" github opennetworkinglab onos --category pull_request -t "${API_KEY}" --sleep-for-rate >> .perceval_onos.github.log || exit 2
  p2o.py --enrich --index github_raw --index-enrich github -e http://localhost:9200 --no_inc --debug --db-host localhost --db-sortinghat shdb --db-user shuser --db-password "${PASS}" github opennetworkinglab spring-open --category issue -t "${API_KEY}" --sleep-for-rate >> .perceval_onos.github.log || exit 2
  p2o.py --enrich --index github_raw --index-enrich github -e http://localhost:9200 --no_inc --debug --db-host localhost --db-sortinghat shdb --db-user shuser --db-password "${PASS}" github opennetworkinglab spring-open --category pull_request -t "${API_KEY}" --sleep-for-rate >> .perceval_onos.github.log || exit 2
  p2o.py --enrich --index github_raw --index-enrich github -e http://localhost:9200 --no_inc --debug --db-host localhost --db-sortinghat shdb --db-user shuser --db-password "${PASS}" github opennetworkinglab OnosSystemTest --category issue -t "${API_KEY}" --sleep-for-rate >> .perceval_onos.github.log || exit 2
  p2o.py --enrich --index github_raw --index-enrich github -e http://localhost:9200 --no_inc --debug --db-host localhost --db-sortinghat shdb --db-user shuser --db-password "${PASS}" github opennetworkinglab OnosSystemTest --category pull_request -t "${API_KEY}" --sleep-for-rate >> .perceval_onos.github.log || exit 2
  p2o.py --enrich --index github_raw --index-enrich github -e http://localhost:9200 --no_inc --debug --db-host localhost --db-sortinghat shdb --db-user shuser --db-password "${PASS}" github opennetworkinglab onos-loxi --category issue -t "${API_KEY}" --sleep-for-rate >> .perceval_onos.github.log || exit 2
  p2o.py --enrich --index github_raw --index-enrich github -e http://localhost:9200 --no_inc --debug --db-host localhost --db-sortinghat shdb --db-user shuser --db-password "${PASS}" github opennetworkinglab onos-loxi --category pull_request -t "${API_KEY}" --sleep-for-rate >> .perceval_onos.github.log || exit 2
  p2o.py --enrich --index github_raw --index-enrich github -e http://localhost:9200 --no_inc --debug --db-host localhost --db-sortinghat shdb --db-user shuser --db-password "${PASS}" github opennetworkinglab onos-yang-tools --category issue -t "${API_KEY}" --sleep-for-rate >> .perceval_onos.github.log || exit 2
  p2o.py --enrich --index github_raw --index-enrich github -e http://localhost:9200 --no_inc --debug --db-host localhost --db-sortinghat shdb --db-user shuser --db-password "${PASS}" github opennetworkinglab onos-yang-tools --category pull_request -t "${API_KEY}" --sleep-for-rate >> .perceval_onos.github.log || exit 2
  p2o.py --enrich --index github_raw --index-enrich github -e http://localhost:9200 --no_inc --debug --db-host localhost --db-sortinghat shdb --db-user shuser --db-password "${PASS}" github opennetworkinglab onos-app-samples --category issue -t "${API_KEY}" --sleep-for-rate >> .perceval_onos.github.log || exit 2
  p2o.py --enrich --index github_raw --index-enrich github -e http://localhost:9200 --no_inc --debug --db-host localhost --db-sortinghat shdb --db-user shuser --db-password "${PASS}" github opennetworkinglab onos-app-samples --category pull_request -t "${API_KEY}" --sleep-for-rate >> .perceval_onos.github.log || exit 2
  p2o.py --enrich --index github_raw --index-enrich github -e http://localhost:9200 --no_inc --debug --db-host localhost --db-sortinghat shdb --db-user shuser --db-password "${PASS}" github opennetworkinglab routing --category issue -t "${API_KEY}" --sleep-for-rate >> .perceval_onos.github.log || exit 2
  p2o.py --enrich --index github_raw --index-enrich github -e http://localhost:9200 --no_inc --debug --db-host localhost --db-sortinghat shdb --db-user shuser --db-password "${PASS}" github opennetworkinglab routing --category pull_request -t "${API_KEY}" --sleep-for-rate >> .perceval_onos.github.log || exit 2
  p2o.py --enrich --index github_raw --index-enrich github -e http://localhost:9200 --no_inc --debug --db-host localhost --db-sortinghat shdb --db-user shuser --db-password "${PASS}" github opennetworkinglab spring-open-cli --category issue -t "${API_KEY}" --sleep-for-rate >> .perceval_onos.github.log || exit 2
  p2o.py --enrich --index github_raw --index-enrich github -e http://localhost:9200 --no_inc --debug --db-host localhost --db-sortinghat shdb --db-user shuser --db-password "${PASS}" github opennetworkinglab spring-open-cli --category pull_request -t "${API_KEY}" --sleep-for-rate >> .perceval_onos.github.log || exit 2
else
  echo "Only identities mode"
  p2o.py --only-enrich --refresh-identities --index github_raw --index-enrich github -e http://localhost:9200 --no_inc --debug --db-host localhost --db-sortinghat shdb --db-user shuser --db-password "${PASS}" github opennetworkinglab onos --category issue -t "${API_KEY}" --sleep-for-rate > .perceval_onos.github.log || exit 2
  p2o.py --only-enrich --refresh-identities --index github_raw --index-enrich github -e http://localhost:9200 --no_inc --debug --db-host localhost --db-sortinghat shdb --db-user shuser --db-password "${PASS}" github opennetworkinglab onos --category pull_request -t "${API_KEY}" --sleep-for-rate >> .perceval_onos.github.log || exit 2
  p2o.py --only-enrich --refresh-identities --index github_raw --index-enrich github -e http://localhost:9200 --no_inc --debug --db-host localhost --db-sortinghat shdb --db-user shuser --db-password "${PASS}" github opennetworkinglab spring-open --category issue -t "${API_KEY}" --sleep-for-rate >> .perceval_onos.github.log || exit 2
  p2o.py --only-enrich --refresh-identities --index github_raw --index-enrich github -e http://localhost:9200 --no_inc --debug --db-host localhost --db-sortinghat shdb --db-user shuser --db-password "${PASS}" github opennetworkinglab spring-open --category pull_request -t "${API_KEY}" --sleep-for-rate >> .perceval_onos.github.log || exit 2
  p2o.py --only-enrich --refresh-identities --index github_raw --index-enrich github -e http://localhost:9200 --no_inc --debug --db-host localhost --db-sortinghat shdb --db-user shuser --db-password "${PASS}" github opennetworkinglab OnosSystemTest --category issue -t "${API_KEY}" --sleep-for-rate >> .perceval_onos.github.log || exit 2
  p2o.py --only-enrich --refresh-identities --index github_raw --index-enrich github -e http://localhost:9200 --no_inc --debug --db-host localhost --db-sortinghat shdb --db-user shuser --db-password "${PASS}" github opennetworkinglab OnosSystemTest --category pull_request -t "${API_KEY}" --sleep-for-rate >> .perceval_onos.github.log || exit 2
  p2o.py --only-enrich --refresh-identities --index github_raw --index-enrich github -e http://localhost:9200 --no_inc --debug --db-host localhost --db-sortinghat shdb --db-user shuser --db-password "${PASS}" github opennetworkinglab onos-loxi --category issue -t "${API_KEY}" --sleep-for-rate >> .perceval_onos.github.log || exit 2
  p2o.py --only-enrich --refresh-identities --index github_raw --index-enrich github -e http://localhost:9200 --no_inc --debug --db-host localhost --db-sortinghat shdb --db-user shuser --db-password "${PASS}" github opennetworkinglab onos-loxi --category pull_request -t "${API_KEY}" --sleep-for-rate >> .perceval_onos.github.log || exit 2
  p2o.py --only-enrich --refresh-identities --index github_raw --index-enrich github -e http://localhost:9200 --no_inc --debug --db-host localhost --db-sortinghat shdb --db-user shuser --db-password "${PASS}" github opennetworkinglab onos-yang-tools --category issue -t "${API_KEY}" --sleep-for-rate >> .perceval_onos.github.log || exit 2
  p2o.py --only-enrich --refresh-identities --index github_raw --index-enrich github -e http://localhost:9200 --no_inc --debug --db-host localhost --db-sortinghat shdb --db-user shuser --db-password "${PASS}" github opennetworkinglab onos-yang-tools --category pull_request -t "${API_KEY}" --sleep-for-rate >> .perceval_onos.github.log || exit 2
  p2o.py --only-enrich --refresh-identities --index github_raw --index-enrich github -e http://localhost:9200 --no_inc --debug --db-host localhost --db-sortinghat shdb --db-user shuser --db-password "${PASS}" github opennetworkinglab onos-app-samples --category issue -t "${API_KEY}" --sleep-for-rate >> .perceval_onos.github.log || exit 2
  p2o.py --only-enrich --refresh-identities --index github_raw --index-enrich github -e http://localhost:9200 --no_inc --debug --db-host localhost --db-sortinghat shdb --db-user shuser --db-password "${PASS}" github opennetworkinglab onos-app-samples --category pull_request -t "${API_KEY}" --sleep-for-rate >> .perceval_onos.github.log || exit 2
  p2o.py --only-enrich --refresh-identities --index github_raw --index-enrich github -e http://localhost:9200 --no_inc --debug --db-host localhost --db-sortinghat shdb --db-user shuser --db-password "${PASS}" github opennetworkinglab routing --category issue -t "${API_KEY}" --sleep-for-rate >> .perceval_onos.github.log || exit 2
  p2o.py --only-enrich --refresh-identities --index github_raw --index-enrich github -e http://localhost:9200 --no_inc --debug --db-host localhost --db-sortinghat shdb --db-user shuser --db-password "${PASS}" github opennetworkinglab routing --category pull_request -t "${API_KEY}" --sleep-for-rate >> .perceval_onos.github.log || exit 2
  p2o.py --only-enrich --refresh-identities --index github_raw --index-enrich github -e http://localhost:9200 --no_inc --debug --db-host localhost --db-sortinghat shdb --db-user shuser --db-password "${PASS}" github opennetworkinglab spring-open-cli --category issue -t "${API_KEY}" --sleep-for-rate >> .perceval_onos.github.log || exit 2
  p2o.py --only-enrich --refresh-identities --index github_raw --index-enrich github -e http://localhost:9200 --no_inc --debug --db-host localhost --db-sortinghat shdb --db-user shuser --db-password "${PASS}" github opennetworkinglab spring-open-cli --category pull_request -t "${API_KEY}" --sleep-for-rate >> .perceval_onos.github.log || exit 2
fi
