#!/bin/bash
# To run inside SDS container
DA_DS=git DA_GIT_AFFILIATION_API_URL=$AFFILIATION_API_URL DA_GIT_DB_HOST=$SH_HOST DA_GIT_DB_NAME=$SH_DB DA_GIT_DB_USER=$SH_USER DA_GIT_DB_PASS=$SH_PASS DA_GIT_DB_PORT=$SH_PORT DA_GIT_ES_URL=$SDS_ES_URL DA_GIT_URL='https://github.com/LF-Engineering/sync-data-sources' DA_GIT_PROJECT=LF DA_GIT_ENRICH=1 DA_GIT_DEBUG=1 PROJECT_SLUG='cncf/k8s' DA_GIT_RAW_INDEX=test-git-raw DA_GIT_RICH_INDEX=test-git dads
