#!/bin/bash
# To run inside SDS container
DA_DS=github DA_GITHUB_AFFILIATION_API_URL=$AFFILIATION_API_URL DA_GITHUB_DB_HOST=$SH_HOST DA_GITHUB_DB_NAME=$SH_DB DA_GITHUB_DB_USER=$SH_USER DA_GITHUB_DB_PASS=$SH_PASS DA_GITHUB_DB_PORT=$SH_PORT DA_GITHUB_ES_URL=$SDS_ES_URL DA_GITHUB_TOKENS=$SDS_GITHUB_OAUTH DA_GITHUB_ORG=kubernetes DA_GITHUB_REPO=cloud-provider-vsphere DA_GITHUB_PROJECT=Kubernetes DA_GITHUB_ENRICH=1 DA_GITHUB_DEBUG=1 PROJECT_SLUG='cncf/k8s' DA_GITHUB_RAW_INDEX=sds-cncf-k8s-github-issue-raw DA_GITHUB_RICH_INDEX=sds-cncf-k8s-github-issue DA_GITHUB_CATEGORY=issue dads
