#!/bin/bash
#SDS_SKIP_P2O=1 SDS_SKIP_DATA=1 SDS_SKIP_AFFS=1 SDS_SKIP_ES_DATA=1 SDS_SKIP_ES_LOG=1 SDS_SKIP_PROJECT=1 SDS_SKIP_PROJECT_TS=1 SDS_SKIP_SORT_DURATION=1 SDS_SKIP_SSAW=1 syncdatasources 2>&1 | tee run.log
SDS_SKIP_P2O=1 SDS_SKIP_DATA=1 SDS_SKIP_AFFS=1 SDS_SKIP_ES_DATA=1 SDS_SKIP_ES_LOG=1 SDS_SKIP_PROJECT=1 SDS_SKIP_PROJECT_TS=1 SDS_SKIP_SORT_DURATION=1 SDS_SKIP_SSAW=1 SDS_SKIP_METADATA=1 SDS_SKIP_MERGE=1 SDS_SKIP_F_ALIASES=1 SDS_SKIP_ORG_MAP=1 SDS_SKIP_EXTERNAL=1 syncdatasources 2>&1 | tee run.log
