FROM golang:1.17 AS builder
RUN apt-get update -y && apt-get upgrade -y && apt-get install -y ca-certificates openssh-client git make
WORKDIR /go/src/github.com/LF-Engineering/
RUN git clone https://github.com/LF-Engineering/sync-data-sources
WORKDIR /go/src/github.com/LF-Engineering/sync-data-sources/sources
RUN ls -l /go/src/github.com/LF-Engineering/sync-data-sources/sources
RUN make -f ./Makefile dockerinstall
FROM alpine
RUN apk add git bash
COPY docker-images/.gitconfig /root/.gitconfig
COPY docker-images/scripts/*.sh /
COPY --from=builder /go/bin/syncdatasources /usr/bin/
RUN mkdir /data
CMD /bin/bash
